language: node_js

node_js:
  - '6'

sudo: false

git:
  depth: 1

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

branches:
  except:
  - gh-pages

script:
  - "npm run coveralls"
